### ISSUE TITLE
How to add a title / text?

### ISSUE THREAD

**Issue by danielnjoo** [derhuerst/svg-radar-chart#7]
Hi Jannis! I guess this is potentially a feature request or a question if you don't have the time.

SVG scares (horrifies me), but your package works wonders and I'm super happy with it. I'm trying to add a title / text to my charts though and I'm not sure where it might go in the package code... do you think you could point me in the right direction / towards the right resources? Thanks!

**Comment by derhuerst** [comment]
Hey Daniel!

Have you done HTML & CSS before? Because actually SVG is not that different. The major difference is that SVG is more about distinctly positioning items (it has a layout system different than the box model, flexbox model, etc that HTML has), but you style items using CSS and the properties are very similar, e.g. `stroke-width` (instead of `border-width`). MDN has [a pretty good introduction to SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial) as well as [a reference](https://developer.mozilla.org/en-US/docs/Web/SVG).

`svg-radar-chart` returns a tree of SVG elements in a certain structure created using [virtual-dom](https://github.com/Matt-Esch/virtual-dom).

The reason I didn't add a title option is to keep this tool focused. There are too many options related to text, so I'd be adding more and more over time. Rather, I tried to keep this tool as "accessible to modifications as possible, which is why the returned tree does not include the `<svg>` root element and the readme tells you how to wrap it around. (Is that understandable btw?)

You should be able to add a `<text>` element similarly:

```js
const svg = `
<svg version="1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
	<style>
		/* all your CSS goes here */
	</style>
	<text x="1" y="1" font-size="10">Hello World!</text>
	${stringify(chart)}
</svg>
`
```

**Comment by derhuerst** [comment]
Please reopen if you encounter any issues.

**Comment by danielnjoo** [comment]
Hey Jannis, thanks for the super prompt and thorough response.

Hm I guess I was irrationally afraid of SVGs because of prior experience with trying to create SVG animations. Static SVGs are in fact quite friendly and as you noted similar to HTML. Codepen turned out to be quite useful as well.
